# GitHub Action for deploying the Reflex application to Reflex Cloud

name: Deploy Reflex App

# Triggers the workflow on push events but only for the "main" branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Reflex Cloud
        uses: reflex-dev/reflex-deploy-action@v1
        with:
          # Required: The authentication token for Reflex Cloud.
          # Store this in your GitHub repository's secrets with the name REFLEX_AUTH_TOKEN.
          auth_token: ${{ secrets.REFLEX_AUTH_TOKEN }}
          
          # Required: The ID of the project you want to deploy to.
          # Store this in your GitHub repository's secrets with the name REFLEX_PROJECT_ID.
          project_id: ${{ secrets.REFLEX_PROJECT_ID }}
          
          # Optional: The directory containing your Reflex app.
          # Our app is in the 'python_xray_argo' directory.
          app_directory: "python_xray_argo"
          
          # Optional: The Python version to use for the deployment environment.
          python_version: "3.11"

