name: Deploy to Reflex Hosting

on:
  push:
    branches:
      - main  # 或者你的主分支名

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # 推荐使用 Reflex 支持的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install reflex

      - name: Initialize Reflex
        run: reflex init

      - name: Deploy to Reflex Hosting
        env:
          REFLEX_AUTH_TOKEN: ${{ secrets.REFLEX_AUTH_TOKEN }}
        run: reflex deploy
