name: Deploy Reflex App Manually

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1: 获取您的代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤 2: 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 步骤 3: 安装项目依赖
      # 这一步会根据 requirements.txt 安装我们锁定的 reflex==0.3.9 版本
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 步骤 4: 执行部署命令
      # 我们直接运行 reflex deploy 命令，并通过 env 设置认证令牌
      # --non-interactive 参数确保它在自动化脚本中能顺利运行
      - name: Run Reflex Deploy
        env:
          REFLEX_AUTH_TOKEN: ${{ secrets.REFLEX_AUTH_TOKEN }}
        run: reflex deploy --project ${{ secrets.REFLEX_PROJECT_ID }} --non-interactive
