name: Deploy Reflex App

on:
  #schedule:
   # - cron: '0 0 */3 * *'  # 每3天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Reflex Cloud
        uses: reflex-dev/reflex-deploy-action@v1
        with:
          auth_token: ${{ secrets.REFLEX_PROJECT_ID }}
          project_id: ${{ secrets.REFLEX_PROJECT_ID }}
          app_directory: "cnmgfw-reflex-hello" # Optional, defaults to root
          extra_args: "--env THIRD_PARTY_APIKEY=***" # Optional
          python_version: "3.12" # Optional
